plugins:
  - jekyll-feed
theme: jekyll-theme-hacker
author: Mike Levin
permalink: /:slug/
gaid: G-0H19QDRNTL
title: Levinux | Levinux.com
description: Welcome to the Levinux | Levinux.com Website!
tagline: tagline
welcome: Welcome to the Levinux Website!
apex: Levinux.com