plugins:
  - jekyll-feed
  - jekyll-sitemap
theme: jekyll-theme-hacker
author: Mike Levin
permalink: /:slug/
gaid: G-0H19QDRNTL
title: Levinux | Levinux.com
description: Welcome to the Levinux | Levinux.com Website!
tagline: Levinux
welcome: Welcome to the Levinux Website!
apex: Levinux.com