plugins:
  - jekyll-feed
theme: jekyll-theme-hacker
author: Mike Levin
permalink: /:slug/
gaid: G-0H19QDRNTL
title: Levinux | Levinux.com
description: Welcome to Levinux | Levinux.com
tagline: Levinux
apex: Levinux.com